# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccradar" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "b07703495b09c9205bb85a857c49ab122b7dd5d3e0d532f8d28c2c0a642ae780"
      url "https://github.com/atarnvik/ccradar/releases/download/v#{version}/ccradar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "758280b097c7be2c892075cb8d9f5067a7cb03db412805d66f2d60adf6a302b6"
      url "https://github.com/atarnvik/ccradar/releases/download/v#{version}/ccradar_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ccradar"
  desc "Dashboard to find, focus, and resume Claude Code sessions across terminals"
  homepage "https://github.com/atarnvik/ccradar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccradar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccradar"]
    end
  end

  # No zap stanza required

end
