# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccradar" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "8a36a2b78baa7094f3642b52bc2a69ca9a6c9ed1cd7d80cf76619a7094dd9614"
      url "https://github.com/atarnvik/ccradar/releases/download/v#{version}/ccradar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2943e619f7ac6d23903f293a7853c819b2d544de97a2371a55400ce99ac114da"
      url "https://github.com/atarnvik/ccradar/releases/download/v#{version}/ccradar_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ccradar"
  desc "Dashboard to find, focus, and resume Claude Code sessions across terminals"
  homepage "https://github.com/atarnvik/ccradar"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "terminal-notifier",
    ]

  binary "ccradar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccradar"]
    end
  end

  # No zap stanza required

end
