# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccradar" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "532221770dbc0d33bf97f2c71275c52d2df21cde7c943aec456c78a4966d0388"
      url "https://github.com/atarnvik/ccradar/releases/download/v#{version}/ccradar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb54b731e1d698669458a78f52d57e7856e0976aead8e1b9eb02ac07af91238e"
      url "https://github.com/atarnvik/ccradar/releases/download/v#{version}/ccradar_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ccradar"
  desc "Dashboard to find, focus, and resume Claude Code sessions across terminals"
  homepage "https://github.com/atarnvik/ccradar"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "terminal-notifier",
    ]

  binary "ccradar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccradar"]
    end
  end

  # No zap stanza required

end
